### ISSUE TITLE
Possible unwrap of None value

### ISSUE THREAD

**Issue by michaeljfazio** [primetype/poldercast#19]
The following call to unwrap can cause panics:

https://github.com/primetype/poldercast/blob/f8821864cf4b60713454684f8dac5ece91a3df38/src/poldercast/rings.rs#L250

Created [fix on release branch of v0.11.2](https://github.com/michaeljfazio/poldercast/commit/28f3aff52d1dca94c9f8b463c94ae56205a5b889) but cannot merge unless an upstream release branch is created and pushed.

**Comment by NicolasDP** [comment]
thanks
