### ISSUE TITLE
Poldercats should support static topology

### ISSUE THREAD

**Issue by mark-stopka** [primetype/poldercast#21]
If Poldercast would be the future pub/sub for Cardano next-gen as indicated by [CH in this AMA 03-Jan-2020](https://www.youtube.com/watch?v=CBGYIHb600w&feature=youtu.be&t=2272), logs of issues should be made that are known for the current Poldercast implementation.

It's known from the Cardano Shelley ITNv1 running [Jormungandr](https://github.com/input-output-hk/jormungandr), operators would like the ability to add and keep their operated nodes in the topology, however Jormungandr, nor does Poldercast library enable static topology layers.

It was a justification given in the #16 PolderCast Layers Not Communicating that the deviation from the paper architecture and individual layers not communication was to enable layer flexibility such as adding custom topology layers.

## Static topology layer
Static topology layer should be added as the next topology, pub/sub nodes should be able to add static network topology that is to have some functionality that indicate the nodes within static topology are more trusted then the otherwise discovered peers.

Effectively this should enable Jormungandr node operators to add their relay nodes to their leader node and keep them there. This is basically a dependency for [input-output-hk/jormungandr/#883](https://github.com/input-output-hk/jormungandr/issues/883).

**Comment by mark-stopka** [comment]
Linking relevant issue #18 Document the implementation decisions differences from the paper

**Comment by NicolasDP** [comment]
So this is an IOHK/Jormungandr specific issue. Anyone can write a `Layer` to implement such a feature and it would be better to live in within that product specifically. I.e. there is not much that needs to be done in this repo in order to have such a feature, this is something that can be done directly on the client side by implementing a `Layer`.

**Comment by NicolasDP** [comment]
adding the links to the relevant part:

* implement a `Layer`: https://docs.rs/poldercast/0.12.0/poldercast/trait.Layer.html
* add it to the `Topology`: https://docs.rs/poldercast/0.12.0/poldercast/struct.Topology.html#method.add_layer
